/**
 * narrator.ts — AI narrative generation for traced code flows.
 *
 * Takes a TracedFlow (from flow-tracer) and a user prompt describing
 * what they want to understand. Returns a NarratedFlow with per-step
 * human-readable explanations generated by the LLM.
 */

import {
  getProvider,
  getOpenAIClient,
  getAnthropicClient,
  LLM_MODEL,
  LLM_MAX_TOKENS,
} from "@/src/modules/llm/provider";
import type { TracedFlow, FlowStep } from "./flow-tracer";

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface NarratedStep {
  order: number;
  heading: string;
  narrative: string;
  filePath: string;
  startLine: number;
  endLine: number;
  code: string;
  symbolName: string;
  keyInsight: string;
}

export interface NarratedFlow {
  title: string;
  overview: string;
  steps: NarratedStep[];
  conclusion: string;
}

// ---------------------------------------------------------------------------
// Prompt construction
// ---------------------------------------------------------------------------

const NARRATOR_SYSTEM_PROMPT = `You are a senior developer narrating a code flow for a teammate.
For each step, explain what happens, why it matters, and how it connects to the next step.
Use the actual function/variable names. Reference specific line numbers.
Write in second person: "When you call X, it first Y, then Z..."
Keep each step explanation to 2-4 sentences. Be concrete, not abstract.

You MUST respond with valid JSON matching this exact structure:
{
  "title": "string — short title for this flow (5-10 words)",
  "overview": "string — 2-3 sentence summary of the entire flow",
  "steps": [
    {
      "order": number,
      "heading": "string — e.g. 'Step 1: Validating the session'",
      "narrative": "string — 2-4 sentence explanation of what this step does",
      "keyInsight": "string — one-sentence takeaway about this step"
    }
  ],
  "conclusion": "string — 1-2 sentence wrap-up of what was accomplished"
}

Do not include markdown code fences around the JSON. Output raw JSON only.`;

function buildNarratorPrompt(
  tracedFlow: TracedFlow,
  userPrompt: string,
): string {
  const allSteps = [tracedFlow.entryPoint, ...tracedFlow.steps];

  const stepsText = allSteps
    .map((step: FlowStep) => {
      const relationNote =
        step.incomingRelation
          ? ` (reached via: ${step.incomingRelation})`
          : " (entry point)";

      return [
        `--- Step ${step.order}${relationNote} ---`,
        `Symbol: ${step.symbolName} (${step.symbolKind})`,
        `File: ${step.filePath}:L${step.startLine}-L${step.endLine}`,
        `Code:`,
        step.code.slice(0, 800), // truncate very long code snippets
        "",
      ].join("\n");
    })
    .join("\n");

  return [
    `## User Request`,
    userPrompt,
    "",
    `## Traced Flow (${allSteps.length} steps across ${tracedFlow.totalFiles} files)`,
    stepsText,
    "",
    `## Instructions`,
    `Generate the narrative JSON for the ${allSteps.length} steps above.`,
    `The "steps" array in your JSON must have exactly ${allSteps.length} entries,`,
    `one for each step (order 0 through ${allSteps.length - 1}).`,
    `Step 0 is the entry point.`,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// LLM calls
// ---------------------------------------------------------------------------

async function callOpenAI(systemPrompt: string, userMessage: string): Promise<string> {
  const client = getOpenAIClient();
  const response = await client.chat.completions.create({
    model: LLM_MODEL,
    max_tokens: LLM_MAX_TOKENS,
    messages: [
      { role: "system", content: systemPrompt },
      { role: "user", content: userMessage },
    ],
    response_format: { type: "json_object" },
  });
  return response.choices[0]?.message?.content ?? "{}";
}

async function callAnthropic(systemPrompt: string, userMessage: string): Promise<string> {
  const client = getAnthropicClient();
  const response = await client.messages.create({
    model: LLM_MODEL,
    max_tokens: LLM_MAX_TOKENS,
    system: systemPrompt,
    messages: [{ role: "user", content: userMessage }],
  });

  const textBlock = response.content.find((b) => b.type === "text");
  if (!textBlock || textBlock.type !== "text") return "{}";

  // Strip markdown code fences if Anthropic wraps the JSON
  const raw = textBlock.text.trim();
  const fenceMatch = raw.match(/```(?:json)?\s*([\s\S]*?)```/);
  return fenceMatch ? fenceMatch[1].trim() : raw;
}

// ---------------------------------------------------------------------------
// Response parsing
// ---------------------------------------------------------------------------

interface LLMStep {
  order?: number;
  heading?: string;
  narrative?: string;
  keyInsight?: string;
}

interface LLMResponse {
  title?: string;
  overview?: string;
  steps?: LLMStep[];
  conclusion?: string;
}

function parseNarratorResponse(
  raw: string,
  tracedFlow: TracedFlow,
): NarratedFlow {
  let parsed: LLMResponse;
  try {
    parsed = JSON.parse(raw) as LLMResponse;
  } catch {
    // If the LLM didn't return valid JSON, build a minimal fallback
    parsed = {};
  }

  const allSteps = [tracedFlow.entryPoint, ...tracedFlow.steps];
  const llmSteps: LLMStep[] = Array.isArray(parsed.steps) ? parsed.steps : [];

  const narratedSteps: NarratedStep[] = allSteps.map((step, idx) => {
    const llmStep = llmSteps[idx] ?? {};
    const stepNum = step.order;

    return {
      order: stepNum,
      heading:
        typeof llmStep.heading === "string" && llmStep.heading
          ? llmStep.heading
          : `Step ${stepNum}: ${step.symbolName}`,
      narrative:
        typeof llmStep.narrative === "string" && llmStep.narrative
          ? llmStep.narrative
          : `Execution reaches \`${step.symbolName}\` (${step.symbolKind}) in ${step.filePath}.`,
      filePath: step.filePath,
      startLine: step.startLine,
      endLine: step.endLine,
      code: step.code,
      symbolName: step.symbolName,
      keyInsight:
        typeof llmStep.keyInsight === "string" && llmStep.keyInsight
          ? llmStep.keyInsight
          : `${step.symbolName} is a ${step.symbolKind} in ${step.filePath.split("/").pop()}.`,
    };
  });

  return {
    title:
      typeof parsed.title === "string" && parsed.title
        ? parsed.title
        : "Code Flow Walkthrough",
    overview:
      typeof parsed.overview === "string" && parsed.overview
        ? parsed.overview
        : `This flow traces execution through ${tracedFlow.totalSymbols} symbols across ${tracedFlow.totalFiles} files.`,
    steps: narratedSteps,
    conclusion:
      typeof parsed.conclusion === "string" && parsed.conclusion
        ? parsed.conclusion
        : `The flow completes after traversing ${tracedFlow.totalSymbols} symbols.`,
  };
}

// ---------------------------------------------------------------------------
// Main export
// ---------------------------------------------------------------------------

/**
 * Generate a narrative walkthrough for a traced code flow.
 *
 * @param tracedFlow  - Output from flow-tracer.traceFlow()
 * @param userPrompt  - The user's description of what they want to understand
 */
export async function narrateFlow(
  tracedFlow: TracedFlow,
  userPrompt: string,
): Promise<NarratedFlow> {
  const userMessage = buildNarratorPrompt(tracedFlow, userPrompt);

  let rawResponse: string;
  const provider = getProvider();

  if (provider === "openai") {
    rawResponse = await callOpenAI(NARRATOR_SYSTEM_PROMPT, userMessage);
  } else {
    rawResponse = await callAnthropic(NARRATOR_SYSTEM_PROMPT, userMessage);
  }

  return parseNarratorResponse(rawResponse, tracedFlow);
}
